# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170413_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modernarealength',
            old_name='gid',
            new_name='modernarealengthid',
        ),
        migrations.AddField(
            model_name='modernarealength',
            name='modernid',
            field=models.ForeignKey(db_column='modernid', default=27546, on_delete=django.db.models.deletion.CASCADE, to='api.Modern'),
        ),
    ]
