# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170413_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arendtregions',
            name='albersgeom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3338),
        ),
    ]
