# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_arendtregions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Burgessregions',
        ),
        migrations.DeleteModel(
            name='Ergi',
        ),
        migrations.DeleteModel(
            name='Ergibins',
        ),
        migrations.DeleteModel(
            name='Icesat',
        ),
        migrations.DeleteModel(
            name='Lamb',
        ),
        migrations.DeleteModel(
            name='MasconFit',
        ),
        migrations.DeleteModel(
            name='MasconSolution',
        ),
        migrations.DeleteModel(
            name='Prism',
        ),
        migrations.DeleteModel(
            name='SnowradarOld',
        ),
        migrations.DeleteModel(
            name='SweingestLines',
        ),
        migrations.DeleteModel(
            name='SweingestMetadata',
        ),
    ]
