# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice2o', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modern',
            old_name='gid',
            new_name='modernid',
        ),
    ]
