# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice2o', '0004_auto_20170413_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arendtregions',
        ),
    ]
